services:
- docker
script:
- docker build --tag todo-app-dev --target development .
- docker build --tag todo-app-test --target test .
- docker build --target production --tag anniebedford/todo-app-prod . 
#docker push registry.heroku.com/devops-dotnet/web
- docker run -e API_KEY -e SERVER_TOKEN -e BOARD_ID todo-app-test
#- echo $DOCKER_PW | docker login -u $DOCKER_USER --password-stdin

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: main
  
notifications:
  slack:
    secure: HJQ/XLQJ4fgGY53qi/UMQ0waUvL+gyKKMUoBj8cCOF2P8zzxGw8/fpWAFaivyqfjs1qRrSX4tg+YBWkmTsJ/MQpKBlPNyUtwfaMbYlQCMaDk15jbkyisehgUDac0djOhyuHgaZMeXOpH+U3O7n1tOxigY7ey57GgMQv8gxHtaMhT/qLP/bokMy1QplVlzg2+OAAp0lUS1B76GWTLd498DDifukvBKMqq3nnEW6s3iGMCP2zG/SNUWfFHcZcilWQzT5XGqZ2/fKr20ROGR56UB6uC75fHx4s1gobz345MmsrvmeBa7ptHnNL/3JFxTM7cW52jQfvYeekHwJY/ScnGAM2/1sXkLpFiQN8yqydbd0o7/7rWdEGEWIaT3/bXg+RW213rYOV3h5vAJcUYKYAiDH29xMxXI29LoQet/oe2gxVPFORQ0kj3QJ9Tk2VvlnhFKjjvuCl2mZfVxocmZUNbJykd9cEkANKhyUvuQG94kQ4zP8e7y7pdUpLhViTlKN0WgKRxxADK54VWMgZIxYCtx8TUOPTBLKSQhcO5e/Cri57dpgoo8dPNZg8A3tmdHpctuwTWCkiFd/VLzaB4En+QggDitIDu2t9g/uSwI6Q0EokyQFw0j8qNA5tHQmhO5NiHJSEVAv7ceV0hMUL4AG/EJ3I4GDk3p1i6HeOTJUxkMLQ=
env:
  global:
    secure: DY0cAS25m6LeX9FxYWwSdXR2kBx/6A1xBk+V6RMxCXCIMXpbxjXGcdxY0SPjpmqg2AjjM1csCRhdGtWkZqAESKCjUQbyHlHJde5jmx3pwkouN6oimx7SaDws4KgVGTgjBfhNJoQDSkIOy9I7+aUHVHVrboa1xFY/7Cid5SvSA1ekP0u4xeE2tXvUqaI3MbE25rOF34nZR6kqjlQGZGGzd042cEvG4y41IHeLPZfjELMzphkSHgXKNyLh39mBnhv3gUxSV6O0u7o/KZBrK8wTBXvQAZF8BnYK/CKiBTazKjttLUovTKTE9XgUnJ/DjhngylNoV8Y6D0/6jxDnJRDM1G5mtTVsQmu/mZ5aDl80UN+kVI1HdkLFRg1V3Qlp31D0EL3oX0NouaDbaBytg+vB2u5Vn9zkFiw7KMGyIgCKnk17mBsDrmYfsgs8l0yuKtl7t1ea3dhWeM2LVLAbhtiEqkX71OAlgZxEl8aAla55ZTDYyiq8zSNHv2t+bDBE5XSk0ZztH/U1LvQ0Ntcs3Dih0EPA0hiIQ/SInqxzM7EHFxffqwLR8etO86zYvlsQIQ8txVnedWnj5wn5oKQysRikpRZUbOCf0V08TqhkSoc4e6HS52cGJ0ZH48zhIXNSrOUGwOL+Sh6Maoc5L/M3BbI37hRYmVWafERNTzAQeMDm/aY=
