version: "3.9"
services:
  web:
    build: 
        dockerfile: Dockerfile
        target: development
    env_file:
        - .env
    ports:
        - "5000:5000"
    volumes:
        - type: bind 
          source: "C:\\Projects\\DevOps-Course-Starter\\todo_app" 
          target: "/todo_app/todo_app"

