#!/bin/bash
docker build --target production --tag anniebedford/todo-app-prod:latest --tag anniebedford/todo-app-prod:$TRAVIS_COMMIT  .
echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
docker push anniebedford/todo-app-prod:latest
docker push anniebedford/todo-app-prod:$TRAVIS_COMMIT
docker tag anniebedford/todo-app-prod registry.heroku.com/todo-app-ab/web


#echo "$HEROKU_AUTH_TOKEN" | docker login --username=_ registry.heroku.com --password-stdin
echo "$HEROKU_API_KEY" | docker login --username=_ registry.heroku.com   --password-stdin
docker push registry.heroku.com/todo-app-ab/web
heroku container:release web -a todo-app-ab
