# deployment.yaml 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: todo-app 
spec: 
  selector: 
    matchLabels: 
      app: todo-app
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: todo-app
    spec: 
      containers: 
        - name: todo-app 
          image: todo-app:prod 
          imagePullPolicy: Never
          ports: 
          - containerPort: 5000
          env:
          - name: MONGO_CONNECTION
            value: "mongodb+srv"
          - name: MONGO_SRV
            value: "cluster0.l73hh.mongodb.net"
          - name: MONGO_DB
            value: "todo_db"
          - name: MONGO_USER
            value: "admin_user"
          - name: MONGO_PWD
            valueFrom:
              secretKeyRef:
                name: mongo-db-pass
                key: password
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: LOGGLY_TOKEN
            valueFrom:
              secretKeyRef:
                name: loggly-token
                key: token
          - name: OAUTH_CLIENT_ID
            value: "640c2ac9d976df608c2b"
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth-client-secret
                key: secret
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-key
                key: secret